/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.5
 * Generated at: 2023-04-24 20:10:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("              <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD\" crossorigin=\"anonymous\">\n");
      out.write("        <link href=\"css/header.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("        <script src=\"scripts/navigate.js\" type=\"text/javascript\"></script>\n");
      out.write("        <title>Home Page</title>\n");
      out.write("        <style>\n");
      out.write("       .btn-primary {\n");
      out.write("           float: right;\n");
      out.write("       }</style> \n");
      out.write("        <button type=\"button\" onclick=\"location.href = 'login.jsp'\" class=\"btn btn-primary\">Logout</button>\n");
      out.write("    </head>\n");
      out.write("    <body onload=\"showDiv('home');\">\n");
      out.write("    <nav class=\"navbar bg-dark  navbar-expand-lg bg-body-tertiary\" data-bs-theme=\"dark\">\n");
      out.write("      <div class=\"container-fluid\">\n");
      out.write("        <a class=\"navbar-brand\" href=\"#\">Final Project</a>\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNavAltMarkup\" aria-controls=\"navbarNavAltMarkup\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("          <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("        </button>\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarNavAltMarkup\">\n");
      out.write("          <div class=\"navbar-nav\">\n");
      out.write("            <a class=\"nav-link active\" aria-current=\"page\" href=\"javascript:showDiv('home')\">Home</a>\n");
      out.write("            <a class=\"nav-link\" href=\"javascript:showDiv('features')\">Features</a>\n");
      out.write("            <a class=\"nav-link\" href=\"javascript:showDiv('pricing')\">Pricing</a>\n");
      out.write("            <a class=\"nav-link\" href=\"javascript:showDiv('contactus')\">Contact Us</a>\n");
      out.write("            \n");
      out.write("          </div>\n");
      out.write("      <div class=\"col-md-3 text-end\">\n");
      out.write("          <span style=\"color:whitesmoke;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" </span>\n");
      out.write("        \n");
      out.write("      </div>            \n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </nav>\n");
      out.write("        <div id=\"home\"> \n");
      out.write("  <head>\n");
      out.write("    <title>J's Guitar Store</title>\n");
      out.write("              <br>\n");
      out.write("\n");
      out.write("  </head>\n");
      out.write("  <body>\n");
      out.write("    <h1>Welcome to J's Guitar Store!</h1>\n");
      out.write("          <br>\n");
      out.write("    <p>Check out our latest collection of guitars!</p>\n");
      out.write("    <br>\n");
      out.write("\n");
      out.write("    <p>We carry the finest selection of: </p>\n");
      out.write("\n");
      out.write("    <ul>\n");
      out.write("      <li><a>Acoustic Guitars</a></li>\n");
      out.write("      <li><a>Electric Guitars</a></li>\n");
      out.write("      <li><a>Bass Guitars</a></li>\n");
      out.write("          <br>\n");
      out.write("          \n");
      out.write("    </ul>  \n");
      out.write("    <p>\n");
      out.write("        At J's guitars, we are dedicated to providing our customers with the finest handcrafted guitars. \n");
      out.write("        Our passion for music and commitment to excellence drive us to create instruments that are not only \n");
      out.write("        beautiful but also of the highest quality. Each guitar is carefully crafted by skilled artisans using \n");
      out.write("        only the finest materials and techniques. Our goal is to provide musicians with instruments that inspire\n");
      out.write("        them to create and perform at their best. We believe that music has the power to bring people together and enrich our \n");
      out.write("        lives, and we are proud to play a small part in that by providing exceptional guitars.         \n");
      out.write("    </p>\n");
      out.write("    \n");
      out.write("  </body>\n");
      out.write("        </div>\n");
      out.write("         <div id=\"features\"> \n");
      out.write("\n");
      out.write("  <head>\n");
      out.write("    <title>Guitar Features</title>\n");
      out.write("  </head>\n");
      out.write("  <body>\n");
      out.write("    <h1>Guitar Features</h1>\n");
      out.write("              <br>\n");
      out.write("          <br>\n");
      out.write("          <br>\n");
      out.write("\n");
      out.write("    <ul>\n");
      out.write("        <li>\n");
      out.write("        <img src=\"https://qph.cf2.quoracdn.net/main-qimg-9a4c13034f49f5e853db7eaf26662271-pjlq\" alt=\"Guitar 1\">\n");
      out.write("        <h2>G 100</h2>\n");
      out.write("        <ul>\n");
      out.write("          <li>Fully acoustic classical guitar</li>\n");
      out.write("          <li>Maple body</li>\n");
      out.write("          <li>Handmade smooth finish</li>\n");
      out.write("        </ul>\n");
      out.write("      </li>\n");
      out.write("      <li>\n");
      out.write("         <img src= \"https://thumbs.dreamstime.com/b/isolated-classical-guitar-photo-png-format-available-full-transparent-background-54363220.jpg\" alt=\"Guitar 2\">             \n");
      out.write("        <h2>GP 690</h2>\n");
      out.write("        <ul>\n");
      out.write("          <li>Acoustic/Electric classical guitar</li>\n");
      out.write("          <li>Rosewood body, spruce top</li>\n");
      out.write("          <li>Handmade smooth finish</li>\n");
      out.write("          <br>\n");
      out.write("          <br>\n");
      out.write("          <br>\n");
      out.write("          <br>\n");
      out.write("\n");
      out.write("        </ul>        \n");
      out.write("      </li>\n");
      out.write("      <li>\n");
      out.write("        <img src=\"https://m.media-amazon.com/images/I/71Oyto5E2jL._AC_UF894,1000_QL80_.jpg\" alt=\"Guitar 3\">                   \n");
      out.write("        <h2>E 100</h2>\n");
      out.write("        <ul>          \n");
      out.write("          <li>Telecaster style electric guitar</li>\n");
      out.write("          <li>Alder wood body, maple fretboard</li>\n");
      out.write("          <li>Two player Series single-coil Telecaster pickup </li>\n");
      out.write("        </ul>        \n");
      out.write("      </li>      \n");
      out.write("      <li>\n");
      out.write("        <img src=\"https://m.media-amazon.com/images/S/aplus-media/sota/0d722641-32d5-4043-8ef9-c795ea35842a.__CR385,198,1598,989_PT0_SX970_V1___.jpg\" alt=\"Guitar 4\">                    \n");
      out.write("        <h2>E 690</h2>\n");
      out.write("        <ul>\n");
      out.write("          <li>Jaguar style electric guitar</li>\n");
      out.write("          <li>Four magnetic pickups</li>\n");
      out.write("          <li>Alder wood body, maple fretboard</li>\n");
      out.write("        </ul>        \n");
      out.write("      </li>      \n");
      out.write("      <li>\n");
      out.write("         <img src=\"https://images.reverb.com/image/upload/s--leTEj7tg--/a_exif,c_limit,e_unsharp_mask:80,f_auto,fl_progressive,g_south,h_620,q_90,w_620/v1426259338/q61ebpfp1n0jn6gpszjl.jpg\" alt=\"Guitar 5\">                     \n");
      out.write("        <h2>B 43</h2>\n");
      out.write("        <ul>\n");
      out.write("          <li>Acoustic bass guitar</li>\n");
      out.write("          <li>Spruce body</li>\n");
      out.write("          <li>Steel Strings</li>\n");
      out.write("        </ul>        \n");
      out.write("      </li>      \n");
      out.write("      <li>\n");
      out.write("        <img src=\"https://pisces.bbystatic.com/image2/BestBuy_US/images/products/8528/8528901_sa.jpg\" alt=\"Guitar 6\">        \n");
      out.write("        <h2>B 52</h2>\n");
      out.write("        <ul> \n");
      out.write("          <li>Electric bass guitar</li>\n");
      out.write("          <li>Violin style body</li>\n");
      out.write("          <li>Two magnetic pickups</li>\n");
      out.write("\n");
      out.write("        </body>\n");
      out.write("         </div>\n");
      out.write("          <div id=\"pricing\">  <head>\n");
      out.write("    <title>Acoustic Guitars</title>\n");
      out.write("  </head>\n");
      out.write("  <body>\n");
      out.write("    <h1>Our Collection of Guitars</h1>\n");
      out.write("          <br>\n");
      out.write("          <br>\n");
      out.write("          <br>\n");
      out.write("\n");
      out.write("    <ul>\n");
      out.write("      <li>\n");
      out.write("        <img src=\"https://qph.cf2.quoracdn.net/main-qimg-9a4c13034f49f5e853db7eaf26662271-pjlq\" alt=\"Guitar 1\">\n");
      out.write("        <h2>G 100</h2>\n");
      out.write("        <p>$100</p>\n");
      out.write("      </li>\n");
      out.write("      <li>\n");
      out.write("        <img src= \"https://thumbs.dreamstime.com/b/isolated-classical-guitar-photo-png-format-available-full-transparent-background-54363220.jpg\" alt=\"Guitar 2\">\n");
      out.write("        <h2>GP 690</h2>\n");
      out.write("        <p>$690</p>\n");
      out.write("          <br>\n");
      out.write("          <br>\n");
      out.write("          <br>\n");
      out.write("          <br>\n");
      out.write("          <br>\n");
      out.write("\n");
      out.write("      </li>\n");
      out.write("      <li>\n");
      out.write("        <img src=\"https://m.media-amazon.com/images/I/71Oyto5E2jL._AC_UF894,1000_QL80_.jpg\" alt=\"Guitar 3\">\n");
      out.write("        <h2>E 100</h2>\n");
      out.write("        <p>$100</p>\n");
      out.write("      </li>\n");
      out.write("      <li>\n");
      out.write("        <img src=\"https://m.media-amazon.com/images/S/aplus-media/sota/0d722641-32d5-4043-8ef9-c795ea35842a.__CR385,198,1598,989_PT0_SX970_V1___.jpg\" alt=\"Guitar 4\">\n");
      out.write("        <h2>E 690</h2>\n");
      out.write("        <p>$690</p>\n");
      out.write("      </li>\n");
      out.write("      <li>\n");
      out.write("        <img src=\"https://images.reverb.com/image/upload/s--leTEj7tg--/a_exif,c_limit,e_unsharp_mask:80,f_auto,fl_progressive,g_south,h_620,q_90,w_620/v1426259338/q61ebpfp1n0jn6gpszjl.jpg\" alt=\"Guitar 5\">\n");
      out.write("        <h2>B 43</h2>\n");
      out.write("        <p>$420</p>\n");
      out.write("      </li>\n");
      out.write("      <li>\n");
      out.write("        <img src=\"https://pisces.bbystatic.com/image2/BestBuy_US/images/products/8528/8528901_sa.jpg\" alt=\"Guitar 6\">\n");
      out.write("        <h2>B 52</h2>\n");
      out.write("        <p>$690</p>\n");
      out.write("      </li>      \n");
      out.write("    </ul>    \n");
      out.write("  </body></div>\n");
      out.write("           <div id=\"contactus\"> \n");
      out.write("  <head>\n");
      out.write("    <title>Contact Us</title>\n");
      out.write("  </head>\n");
      out.write("  <body>\n");
      out.write("    <h1>Contact Us</h1>\n");
      out.write("    <p> J's Guitar Store</p>\n");
      out.write("    <p> Address: 16989 Corinth Street, Lowell, Massechusetts</p>\n");
      out.write("    <p> Phone: (123) 456-7890</p>\n");
      out.write("    <p> Email: info@jsguitarstore.com</p>\n");
      out.write("  </body>\n");
      out.write("           </div>\n");
      out.write("        \n");
      out.write("    </body>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
